#!/bin/bash

tags="$HOME/.dailies.tags"
log="$HOME/.dailies.log"

if [ ! -f "$tags" ]; then
  touch "$tags"
fi

if [ ! -f "$log" ]; then
  touch "$log"
fi

if [ $# -eq 0 ]; then
  "$0" mark
  exit 0
fi

case "$1" in
  "add")
    if [ $# -ne 2 ]; then
      echo "Usage: dailies add <tag>"
      exit 1
    fi

    echo "$2" >> "$tags"
    ;;
  "mark")
    choice="$("$0" remaining | fzf)"
    status="$2"

    if [ -z "$choice" ]; then
      exit 0
    fi

    if [ $# -ne 2 ]; then
      status=$(echo -e "done\nskipped" | fzf)
      if [ -z "$status" ]; then
        status="done"
      fi
    fi

    date="$(date +%Y-%m-%d)"
    printf "%s\n" "$date	$status	$choice" >> "$log"
    "$0" today
    ;;
  "today")
    date="$(date +%Y-%m-%d)"
    grep "$date" "$log"
    ;;
  "remaining")
    date="$(date +%Y-%m-%d)"
    sort "$tags" | while read -r line; do
      isinlog="$(grep "$date	.\+	$line" "$log")"
      if [ -z "$isinlog" ]; then
        echo "$line"
      fi
    done
    ;;
  "count")
    "$0" remaining | wc -l
    ;;
  "summary")
    firstLine="$(head -n 1 "$log")"
    startDate="$(echo "$firstLine" | cut -f1)"
    startEpoch="$(date -d "$startDate" +%s)"
    currentEpoch="$(date +%s)"

    for ((j = 1; j <= 4; j++)); do
      lastNumber=""
      for ((i = startEpoch; i <= currentEpoch; i += 86400)); do
        date="$(date -d "@$i" +%m-%d | tr -d '-')"
        number="$(echo "$date" | cut -c$j)"

        date="$(date -d "@$i" +%Y-%m-%d)"
        currentDate="$(date +%Y-%m-%d)"
        if [ "$date" = "$currentDate" ]; then
          printf " "
        fi

        if [ "$number" != "$lastNumber" ]; then
          printf "%s" "$number"
        else
          printf " "
        fi

        lastNumber="$number"
      done
      echo
    done

    green="$(tput setaf 2)"
    yellow="$(tput setaf 3)"
    red="$(tput setaf 1)"
    reset="$(tput sgr0)"

    sort "$tags" | while read -r line; do
      for ((i = startEpoch; i <= currentEpoch; i += 86400)); do
        date="$(date -d "@$i" +%Y-%m-%d)"
        currentDate="$(date +%Y-%m-%d)"

        isdone="$(grep "$date	done	$line" "$log")"
        isskipped="$(grep "$date	skipped	$line" "$log")"

        if [ "$date" = "$currentDate" ]; then
          printf " "
        fi

        if [ -n "$isdone" ]; then
          printf "%s" "${green}✓${reset}"
        elif [ -n "$isskipped" ]; then
          printf "%s" "${red}✗${reset}"
        else
          printf "%s" "${yellow}.${reset}"
        fi
      done
      printf " %s\n" "$line"
    done
    ;;
  "show")
    cat "$log"
    ;;
  "edit")
    $EDITOR "$tags"
    ;;
  "help")
    echo "Usage: dailies <command>"
    echo "Commands:"
    echo "  add <tag> - add a tag to the list of dailies"
    echo "  mark <status> - mark a daily with a status"
    echo "  today - show today's dailies"
    echo "  remaining - show remaining dailies"
    echo "  count - show the number of remaining dailies"
    echo "  summary - show a summary of dailies"
    echo "  show - show the log"
    echo "  edit - edit the list of tags"
    echo "  help - show this help message"
    ;;
  *)
    echo "Invalid option"
    ;;
esac
