#!/bin/bash

tags="$HOME/.dailies.tags"
log="$HOME/.dailies.log"

if [ ! -f "$tags" ]; then
  touch "$tags"
fi

if [ ! -f "$log" ]; then
  touch "$log"
fi

if [ $# -eq 0 ]; then
  "$0" mark
  exit 0
fi

case "$1" in
  "add")
    if [ $# -ne 2 ]; then
      echo "Usage: dailies add <tag>"
      exit 1
    fi

    echo "$2" >> "$tags"
    ;;
  "mark")
    choice="$("$0" remaining | fzf)"
    status="$2"

    if [ -z "$choice" ]; then
      exit 0
    fi

    if [ $# -ne 2 ]; then
      status=$(echo -e "done\nskipped" | fzf)
      if [ -z "$status" ]; then
        status="done"
      fi
    fi

    date="$(date +%Y-%m-%d)"
    printf "%s\n" "$date	$status	$choice" >> "$log"
    "$0" today
    ;;
  "today")
    date="$(date +%Y-%m-%d)"
    grep "$date" "$log"
    ;;
  "remaining")
    date="$(date +%Y-%m-%d)"
    while read -r line; do
      isinlog="$(grep "$date	.\+	$line" "$log")"
      if [ -z "$isinlog" ]; then
        echo "$line"
      fi
    done < "$tags"
    ;;
  "count")
    "$0" remaining | wc -l
    ;;
  "edit")
    $EDITOR "$tags"
    ;;
  "help")
    echo "Usage: dailies <command>"
    echo "Commands:"
    echo "  add <tag> - add a tag to the list of dailies"
    echo "  mark <status> - mark a daily with a status"
    echo "  today - show today's dailies"
    echo "  remaining - show remaining dailies"
    echo "  count - show the number of remaining dailies"
    echo "  edit - edit the list of tags"
    echo "  help - show this help message"
    ;;
  *)
    echo "Invalid option"
    ;;
esac
